// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AcademyShopAPI.Models;

[Table("Dettaglio_Ordine")]
public partial class DettaglioOrdine
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("FK_ID_Ordine")]
    public int FkIdOrdine { get; set; }

    [Column("FK_ID_Prodotto")]
    public int FkIdProdotto { get; set; }

    public int Quantita { get; set; }

    [ForeignKey("FkIdOrdine")]
    [InverseProperty("DettaglioOrdines")]
    public virtual Ordine FkIdOrdineNavigation { get; set; }

    [ForeignKey("FkIdProdotto")]
    [InverseProperty("DettaglioOrdines")]
    public virtual Prodotto FkIdProdottoNavigation { get; set; }

    //costruttori
    public DettaglioOrdine() { }
    public DettaglioOrdine(int FkIdOrdine, int FkIdProdotto, int Quantita) {
        this.FkIdOrdine = FkIdOrdine;
        this.FkIdProdotto = FkIdProdotto;
        this.Quantita = Quantita;
    }
}