// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AcademyShopAPI.Models;

[Table("Prodotto")]
public partial class Prodotto
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Descrizione { get; set; }

    public int Quantità { get; set; }

    [InverseProperty("FkIdProdottoNavigation")]
    public virtual ICollection<DettaglioOrdine> DettaglioOrdines { get; set; } = new List<DettaglioOrdine>();
}