// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AcademyShopAPI.Models;

[Table("Stato_Ordine")]
public partial class StatoOrdine
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Descrizione { get; set; }

    [InverseProperty("FkIdStatoNavigation")]
    public virtual ICollection<Ordine> Ordines { get; set; } = new List<Ordine>();
}