USE [master]
GO
/****** Object:  Database [AcademyShopDB]    Script Date: 21/05/2024 14:41:26 ******/
CREATE DATABASE [AcademyShopDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AcademyShopDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AcademyShopDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AcademyShopDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AcademyShopDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [AcademyShopDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AcademyShopDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AcademyShopDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AcademyShopDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AcademyShopDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AcademyShopDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AcademyShopDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [AcademyShopDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AcademyShopDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AcademyShopDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AcademyShopDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AcademyShopDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AcademyShopDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AcademyShopDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AcademyShopDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AcademyShopDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AcademyShopDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AcademyShopDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AcademyShopDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AcademyShopDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AcademyShopDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AcademyShopDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AcademyShopDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AcademyShopDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AcademyShopDB] SET RECOVERY FULL 
GO
ALTER DATABASE [AcademyShopDB] SET  MULTI_USER 
GO
ALTER DATABASE [AcademyShopDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AcademyShopDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AcademyShopDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AcademyShopDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AcademyShopDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AcademyShopDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'AcademyShopDB', N'ON'
GO
ALTER DATABASE [AcademyShopDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [AcademyShopDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [AcademyShopDB]
GO
/****** Object:  Table [dbo].[Dettaglio_Ordine]    Script Date: 21/05/2024 14:41:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dettaglio_Ordine](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FK_ID_Ordine] [int] NOT NULL,
	[FK_ID_Prodotto] [int] NOT NULL,
	[Quantita] [int] NOT NULL,
 CONSTRAINT [PK_Dettaglio_Ordine] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ordine]    Script Date: 21/05/2024 14:41:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ordine](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FK_ID_Utente] [int] NOT NULL,
	[Data_Registrazione] [datetime] NOT NULL,
	[Data_Aggiornamento] [datetime] NULL,
	[FK_ID_Stato] [int] NOT NULL,
 CONSTRAINT [PK_Ordine] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Prodotto]    Script Date: 21/05/2024 14:41:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Prodotto](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Descrizione] [varchar](50) NOT NULL,
	[Quantita] [int] NOT NULL,
 CONSTRAINT [PK_Prodotto] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Stato_Ordine]    Script Date: 21/05/2024 14:41:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Stato_Ordine](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Descrizione] [varchar](10) NOT NULL,
 CONSTRAINT [PK_Stato_Ordine] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Utente]    Script Date: 21/05/2024 14:41:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Utente](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Cognome] [varchar](50) NOT NULL,
	[Nome] [varchar](50) NOT NULL,
	[Codice_Fiscale] [char](16) NOT NULL,
	[Data_Registrazione] [datetime] NOT NULL,
	[Password] [char](16) NOT NULL,
 CONSTRAINT [PK_Utente] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Dettaglio_Ordine]  WITH CHECK ADD  CONSTRAINT [FK_Dettaglio_Ordine_Ordine] FOREIGN KEY([FK_ID_Ordine])
REFERENCES [dbo].[Ordine] ([ID])
GO
ALTER TABLE [dbo].[Dettaglio_Ordine] CHECK CONSTRAINT [FK_Dettaglio_Ordine_Ordine]
GO
ALTER TABLE [dbo].[Dettaglio_Ordine]  WITH CHECK ADD  CONSTRAINT [FK_Dettaglio_Ordine_Prodotto] FOREIGN KEY([FK_ID_Prodotto])
REFERENCES [dbo].[Prodotto] ([ID])
GO
ALTER TABLE [dbo].[Dettaglio_Ordine] CHECK CONSTRAINT [FK_Dettaglio_Ordine_Prodotto]
GO
ALTER TABLE [dbo].[Ordine]  WITH CHECK ADD  CONSTRAINT [FK_Ordine_Stato_Ordine] FOREIGN KEY([FK_ID_Stato])
REFERENCES [dbo].[Stato_Ordine] ([ID])
GO
ALTER TABLE [dbo].[Ordine] CHECK CONSTRAINT [FK_Ordine_Stato_Ordine]
GO
ALTER TABLE [dbo].[Ordine]  WITH CHECK ADD  CONSTRAINT [FK_Ordine_Utente] FOREIGN KEY([FK_ID_Utente])
REFERENCES [dbo].[Utente] ([ID])
GO
ALTER TABLE [dbo].[Ordine] CHECK CONSTRAINT [FK_Ordine_Utente]
GO
USE [master]
GO
ALTER DATABASE [AcademyShopDB] SET  READ_WRITE 
GO
